jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Build with Maven
      run: ./mvnw -s .settings.xml clean org.jacoco:jacoco-maven-plugin:prepare-agent
        install -U -P sonar -nsu --batch-mode -Dmaven.test.redirectTestOutputToFile=true
        -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
    - continue-on-error: true
      if: always()
      name: Publish Test Report
      uses: mikepenz/action-junit-report@v2
      with:
        report_paths: '**/surefire-reports/TEST-*.xml'
    - continue-on-error: true
      name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: surefire-reports
        path: '**/surefire-reports/*'
name: Build
on:
  repository_dispatch:
    types: trigger-ga___maven.yaml
